central:
  reports:
    datastores:
      - artifact://nakatanakatana/feed-reader
      - artifact://nakatanakatana/ff
      - artifact://nakatanakatana/gitlab-tools
      - artifact://nakatanakatana/nostr-tools
      - artifact://nakatanakatana/obsidian-clippings-feed
  badges:
    datastores:
      - local://badges
  push:
    enable: true
